# Generated by Django 5.2.17 on 2026-09-29 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(help_text='Ticker del activo (ej. AAPL, BTC-USD)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Nombre descriptivo del activo', max_length=100)),
                ('asset_type', models.CharField(choices=[('STOCK', 'Acción'), ('CRYPTO', 'Criptomoneda')], default='STOCK', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Si el activo se incluye en ingesta y predicciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Activo Financiero',
                'verbose_name_plural': 'Activos Financieros',
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='ModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=50, unique=True)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('confusion_matrix', models.JSONField(default=dict)),
                ('features_used', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Métrica de Modelo ML',
                'verbose_name_plural': 'Métricas de Modelos ML',
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('source', models.CharField(help_text='Fuente de la noticia (ej. Reuters, Yahoo Finance)', max_length=100)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_articles', to='core.asset')),
            ],
            options={
                'verbose_name': 'Noticia Financiera',
                'verbose_name_plural': 'Noticias Financieras',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_label', models.CharField(choices=[('POSITIVE', 'Positivo'), ('NEUTRAL', 'Neutro'), ('NEGATIVE', 'Negativo')], max_length=10)),
                ('sentiment_score', models.FloatField(help_text='Puntaje de sentimiento continuo entre -1.0 y 1.0')),
                ('impact_score', models.FloatField(default=1.0, help_text='Ponderación del impacto estimado (0.0 a 1.0)')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='core.newsarticle')),
            ],
            options={
                'verbose_name': 'Sentimiento de Noticia',
                'verbose_name_plural': 'Sentimientos de Noticias',
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('target_date', models.DateTimeField(db_index=True, help_text='Fecha/Hora objetivo para la cual se predice el cambio')),
                ('predicted_class', models.CharField(choices=[('SUBE', 'Sube'), ('ESTABLE', 'Estable'), ('BAJA', 'Baja')], max_length=10)),
                ('prob_sube', models.FloatField(help_text='Probabilidad de que el precio SUBE (0.0 a 1.0)')),
                ('prob_estable', models.FloatField(help_text='Probabilidad de que el precio se mantenga ESTABLE (0.0 a 1.0)')),
                ('prob_baja', models.FloatField(help_text='Probabilidad de que el precio BAJA (0.0 a 1.0)')),
                ('actual_class', models.CharField(blank=True, choices=[('SUBE', 'Sube'), ('ESTABLE', 'Estable'), ('BAJA', 'Baja')], max_length=10, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('model_version', models.CharField(default='v1.0.0', max_length=50)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='core.asset')),
            ],
            options={
                'verbose_name': 'Predicción',
                'verbose_name_plural': 'Predicciones',
                'ordering': ['-prediction_date'],
            },
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('volume', models.FloatField()),
                ('rsi_14', models.FloatField(blank=True, null=True)),
                ('macd', models.FloatField(blank=True, null=True)),
                ('macd_signal', models.FloatField(blank=True, null=True)),
                ('sma_20', models.FloatField(blank=True, null=True)),
                ('sma_50', models.FloatField(blank=True, null=True)),
                ('volatility_20', models.FloatField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_data', to='core.asset')),
            ],
            options={
                'verbose_name': 'Dato de Mercado',
                'verbose_name_plural': 'Datos de Mercado',
                'ordering': ['-timestamp'],
                'unique_together': {('asset', 'timestamp')},
            },
        ),
    ]
